<?php

declare(strict_types=1);

namespace Brick\Db\Tests\Driver\PDO\Variations;

/**
 * Tests for \Brick\Db\Tests\Driver\PDO\PDOMySQLDriverTest with specific PDO attributes.
 * This class is autogenerated, do not edit.
 */
class PDOMySQLDriver_ERRMODE_SILENT_EMULATE_PREPARES_FALSE_MYSQL_USE_BUFFERED_QUERY_FALSE_Test extends \Brick\Db\Tests\Driver\PDO\PDOMySQLDriverTest
{
    /**
     * @inheritdoc
     */
    protected static function getAttributes() : array
    {
        return [
            \PDO::ATTR_ERRMODE => \PDO::ERRMODE_SILENT,
            \PDO::ATTR_EMULATE_PREPARES => false,
            \PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => false,
        ];
    }
}
